name: Deploy React App to GitHub Pages	

on:
  push:
    branches:
      - gh-pages  # Change this if your default branch is different

jobs:	
  build-and-deploy:	
    runs-on: ubuntu-latest	

    steps:	
      - name: Checkout Repository	
        uses: actions/checkout@v3	

      - name: Setup Node.js	
        uses: actions/setup-node@v3	
        with:	
          node-version: 18	

      - name: Install Dependencies	
        run: npm install	

      - name: Install gh-pages	
        run: npm install -g gh-pages	

      - name: Build React App	
        run: CI=false npm run build	

      - name: Deploy to GitHub Pages	
        run: |	
          git config --global user.email "ktg.sharma725@gmail.com"	
          git config --global user.name "GhastlyWarchief"	
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/GhastlyWarchief/Netflix-GPT.git	
          npm run deploy
